---
kind: pipeline
name: default

steps:
  - name: build-and-test
    image: r.mills.io/prologic/golang-alpine:latest
    commands:
      - make build
      - make test

  - name: build-image-push
    image: r.mills.io/drone_plugins/docker
    settings:
      registry: r.mills.io
      repo: r.mills.io/prologic/rss2twtxt
      tags: latest
      build_args:
        - VERSION=master
        - COMMIT=${DRONE_COMMIT_SHA:0:8}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
      event:
        - push

  - name: build-image-tag
    image: r.mills.io/drone_plugins/docker
    settings:
      registry: r.mills.io
      repo: r.mills.io/prologic/rss2twtxt
      tags: latest
      build_args:
        - VERSION=${DRONE_SEMVER_SHORT##v}
        - COMMIT=${DRONE_COMMIT_SHA:0:8}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
      event:
        - tag

  - name: notify-irc
    image: plugins/webhook
    settings:
      urls:
        - https://msgbus.mills.io/ci.mills.io
    when:
      status:
        - success
        - failure

trigger:
  branch:
    - master
  event:
    - tag
    - push
    - pull_request
